# Generated by Django 3.2.7 on 2021-09-10 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(700), django.core.validators.MinValueValidator(1)]),
        ),
    ]
